version: "3.8"

services:
  # Ethereum Geth Node Configuration
  geth:
    image: ethereum/client-go  # Docker image for Geth
    pull_policy: always  # Always pull the latest image
    container_name: geth  # Container name
    restart: unless-stopped  # Restart policy
    ports:
      - "8545:8545"  # JSON-RPC HTTP service
      - "8546:8546"  # JSON-RPC WebSocket service
      - "8551:8551"  # Execution client API (used by beacon chain)
      - "30303:30303"  # P2P communication
      - "30303:30303/udp"  # P2P communication (UDP)
    volumes:
      - /ethereum-data:/root/.ethereum  # Volume for Ethereum data
    stop_signal: SIGINT  # Stop signal
    stop_grace_period: 2m  # Grace period for stopping
    healthcheck:  # Health check configuration
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
    logging:  # Logging options
      driver: json-file
      options:
        max-size: 2m
        max-file: 10

  # Prysm Beacon Chain Configuration
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain  # Docker image for Prysm
    pull_policy: always  # Always pull the latest image
    container_name: beacon  # Container name
    restart: unless-stopped  # Restart policy
    stop_grace_period: 2m  # Grace period for stopping
    volumes:
      - beacon-data:/path/in/container  # Volume for Prysm data
      - /ethereum-data:/root/.ethereum  # Shared volume for Ethereum data
    depends_on:  # Dependency on Geth
      geth:
        condition: service_healthy
    ports:
      - "4000:4000"  # gRPC server for Prysm
      - "3500:3500"  # P2P communication for Prysm
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --disable-monitoring
      - --rpc-host=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/geth/jwt.hex
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
    logging:  # Logging options
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
