version: '3'
services:
  # Ethereum Node Configuration
  ethereum:
    image: ethereum/client-go:v1.10.23  # Docker image for Ethereum
    restart: always  # Always restart the container if it stops
    container_name: ethereum  # Name of the container
    ports:
      - "8545:8545"  # JSON-RPC HTTP service
      - "30303:30303"  # P2P communication TCP
      - "30303:30303/udp"  # P2P communication UDP
      - "8551:8551"  # Execution client API (used by beacon chain)
    command:
      - --http  # Enable HTTP JSON-RPC API
      - --graphql  # Enable GraphQL API
      - --http.addr 0.0.0.0  # Listen address for HTTP
      - --port 30303  # P2P network port
      - --http.port 8545  # HTTP JSON-RPC port
      - --http.corsdomain "*"  # CORS allowed domains
      - --http.vhosts "*"  # Virtual hosts
    volumes:
      - ./data/ethereum:/root/.ethereum  # Data volume for Ethereum blockchain

  # Lighthouse Beacon Chain Node Configuration
  lighthouse:
    container_name: lighthouse  # Name of the container
    image: sigp/lighthouse:v3.1.0  # Docker image for Lighthouse
    restart: always  # Always restart the container if it stops
    ports:
      - "5052:5052"  # HTTP port for Lighthouse
    command:
      - lighthouse  # Main command to run Lighthouse
      - --network  # Specify the network (mainnet in this case)
      - mainnet
      - beacon  # Run the beacon chain
      - --http  # Enable HTTP API
      - --http-address=0.0.0.0  # Listen address for HTTP
      - --http-port=5052  # HTTP port
      - --execution-endpoint=http://ethereum:8551  # Execution endpoint to connect to Ethereum node
    volumes:
      - ./data/lighthouse:/root/.lighthouse  # Data volume for Lighthouse blockchain
