version: '3'
services:
  ethereum-node:
    build: ./node
    command: "geth --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,web3,net --ws --ws.addr 0.0.0.0 --ws.port 8546 --syncmode snap"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - /ethereum-data:/root/.ethereum
    restart: unless-stopped

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/data:/prometheus
    restart: unless-stopped

  prysm-beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    depends_on:
      - ethereum-node
    ports:
      - "4000:4000"
      - "13000:13000"
    environment:
      - CONFIG_http-web3provider=ws://localhost:8546
    command: ["--accept-terms-of-use"]
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local
  prometheus-storage:
    driver: local
