version: "3.8"

services:
  # Ethereum Geth Node Configuration
  geth:
    image: ethereum/client-go:stable
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    ports:
      - "8545:8545"  # JSON-RPC HTTP service
      - "8546:8546"  # JSON-RPC WebSocket service
      - "8551:8551"  # Execution client API (used by beacon chain)
      - "30303:30303"  # P2P communication
      - "30303:30303/udp"  # P2P communication (UDP)
    volumes:
      - /geth-data:/data/.geth-data
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      [
        # Blockchain sync mode ("snap", "full" or "light")
        "--syncmode=snap",
        # Megabytes of memory allocated to internal caching
        "--cache=8192",
        # Enable the WS-RPC server
        "--ws",
        "--ws.origins=*",
        "--ws.addr=0.0.0.0",
        "--ws.api=eth,net,web3",
        # Enable the HTTP-RPC server
        "--http",
        "--http.api=eth,net,web3,engine,admin",
        "--http.addr=0.0.0.0",
        "--http.vhosts=*",
        "--http.corsdomain=*",
        # Enable GraphQL on the HTTP-RPC server. Note that GraphQL can only be started if an HTTP server is started as well.
        "--graphql",
        "--graphql.corsdomain=*",
        "--graphql.vhosts=*",
        # Enable RPC server
        "--authrpc.addr=0.0.0.0",
        "--authrpc.vhosts=*",
        "--authrpc.jwtsecret=/data/.geth-data/jwt.hex",
        "--authrpc.port=8551",
        "--txlookuplimit=0"
        # Enable metrics collection and reporting
        "--metrics",
        # Ethereum mainnet
        "--mainnet",
        "--ipcpath=/data/.geth-data/geth.ipc"
      ]

  # Prysm Beacon Chain Configuration
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    pull_policy: always
    container_name: beacon
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - /beacon-data:/data/.beacon-data
      - /geth-data:/data/.geth-data
    depends_on:
      geth:
        condition: service_healthy
    ports:
      - "4000:4000"  # gRPC server for Prysm
      - "3500:3500"  # P2P communication for Prysm
    command:
      [
        "--accept-terms-of-use",
        "--disable-monitoring",
        "--rpc-host=0.0.0.0",
        "--execution-endpoint=http://geth:8551",
        "--jwt-secret=/data/.geth-data/jwt.hex",
        "--rpc-host=0.0.0.0",
        "--rpc-port=4000",
        "--grpc-gateway-corsdomain=*",
        "--grpc-gateway-host=0.0.0.0",
        "--grpc-gateway-port=3500"
      ]

volumes:
  geth:
    driver: local
  beacon:
    driver: local
