############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

accept-terms-of-use: true

datadir: /data

#######################
# Connectivity settings
p2p-host-ip: ""
p2p-host-dns: ""

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0

grpc-gateway-host: 0.0.0.0
grpc-gateway-port: 3500
eth-api-port: 3501

# disable scan of local network
p2p-denylist: ["private"]

# changing this also needs to be changed in docker-compose.yaml!
p2p-tcp-port: 13000

p2p-max-peers: 100

##############################
# Connection to geth container
execution-endpoint: http://geth:8551
http-web3provider: http://geth:8545
jwt-secret: jwt.hex

fallback-web3provider: []

block-batch-limit: 512

pyrmont: true

##############################
# Connection to geth container
suggested-fee-recipient: 0x6411D9C53Ba6b59112902b7BfeBfe097F3d1ed9f

# EOF
